apt-cacher-ng:
  container_name: apt-cacher-ng
  image: pataquets/apt-cacher-ng
  # build: .
  # command:
  #   # You can also place the directives below in a 'docker-compose.override.yml' file:
  #   - "Remap-archive: archive.ubuntu.com ; https://mirrors.edge.kernel.org"
  #   - "Remap-security: security.ubuntu.com ; https://mirrors.edge.kernel.org"
  #   - "Remap-archive: archive.ubuntu.com ; http://es.archive.ubuntu.com"
  #   - "-v"
  restart: unless-stopped
  environment:
    - APT_CACHER_NG_TMP_DIR
  # net: host
  ports:
    - "3142:3142"
  volumes:
    # If not specified otherwise via explicit configuration directives
    # or config file, 'LogDir' and 'CacheDir' both default to '/var/tmp/'.
    - ${APT_CACHER_NG_TMP_DIR}:/var/tmp/
